<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>Tests</AssemblyName>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
	  <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.9.4" />
	  <PackageReference Include="NUnit" Version="3.13.2" />
	  <PackageReference Include="NUnit3TestAdapter" Version="3.17.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Migrantoid\Migrantoid.csproj" />
    <ProjectReference Include="..\SecondModule\TestsSecondModule.csproj" />
  </ItemGroup>
</Project>
